<a href="https://colab.research.google.com/github/ShubhamDhakarey/Solve_Question/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6]])


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a.shape

(3, 2)

In [ ]:
b=a.reshape(6,1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [ ]:
print(a.ndim)

2


In [ ]:
import numpy as np
a=np.arange(24)
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
1


In [ ]:
print(a)
b=a.reshape(3,2,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:

print(b.ndim)

3


In [ ]:
c=a.reshape(4,2,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [ ]:

c.ndim

3

In [ ]:
x=np.array([1,2,3,4,5], dtype=np.int8)
x.itemsize


1

In [ ]:
c=np.empty([3,2], dtype=np.float32)
c

array([[9.2878869e-38, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00],
       [1.3722994e-38, 0.0000000e+00]], dtype=float32)

In [ ]:
d=np.zeros(5)
print(d)
print(d.shape)

[0. 0. 0. 0. 0.]
(5,)


In [ ]:
d=np.zeros((2,2), dtype=np.int8)
print(d)
print(d.shape)

[[0 0]
 [0 0]]
(2, 2)


In [ ]:
d=np.zeros((2,2), dtype=[('x','i4'),('y','i4')])
print(d)
print(d.shape)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
(2, 2)


In [ ]:
x=np.ones(5)
print(x)
x.shape

[1. 1. 1. 1. 1.]


(5,)

In [ ]:
x=np.eye(5)
print(x)
x.shape

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


(5, 5)

In [ ]:
x=np.eye((5), dtype=np.int8)
print(x)
x.shape

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


(5, 5)

In [ ]:
x=[1,2,3]
print(type(x))
a=np.asarray(x)
print(type(a))
a

<class 'list'>
<class 'numpy.ndarray'>


array([1, 2, 3])

In [ ]:
x=(1,2,3)
print(type(x))
a=np.asarray(x)
print(type(a))
a

<class 'tuple'>
<class 'numpy.ndarray'>


array([1, 2, 3])

In [ ]:
x={1,2,3}
print(type(x))
a=np.asarray(x)
print(type(a))
a

<class 'set'>
<class 'numpy.ndarray'>


array({1, 2, 3}, dtype=object)

In [ ]:
x=[(1,2,3),(4,5,6)]
print(type(x))
a=np.asarray(x,dtype=object)
print(type(a))
print(a)
a.ndim

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


2

In [ ]:
list=range(5)
it=iter(list)
print(it)
x=np.fromiter(it, dtype=int)
print(x)

[0 1 2 3 4]


In [ ]:
x=np.arange(5)
print(x)

[0 1 2 3 4]


In [ ]:
x=np.arange(1,5,2)
print(x)

[1 3]


In [ ]:
x=np.linspace(10,20,10,endpoint=False)
print(x)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [ ]:
a=np.logspace(1,10,num=10,base=2,dtype=np.int64)
print(a)

[   2    4    8   16   32   64  128  256  512 1024]


In [ ]:
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[1 3 2 5 4]


In [ ]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
print (a ) 
print (b )
print (a + b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
a = np.arange(0,60,5)
a = a.reshape(3,2,2)
print(a)

[[[ 0  5]
  [10 15]]

 [[20 25]
  [30 35]]

 [[40 45]
  [50 55]]]
