<a href="https://colab.research.google.com/github/ShubhamDhakarey/Solve_Question/blob/main/Mid_term.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
a=np.array([3,4,6,10,24,89,45,43,46,99,100])

In [ ]:
a

array([  3,   4,   6,  10,  24,  89,  45,  43,  46,  99, 100])

**Which are not divisible by 3**

In [ ]:
b=a[a%3!=0]

In [ ]:
b

array([  4,  10,  89,  43,  46, 100])

***Which are divisible by 5***

In [ ]:
b=a[a%5==0]

In [ ]:
b

array([ 10,  45, 100])

**which are divisible by 3 and 5**

In [ ]:
b=a[a%3==0]
c=b[b%5==0]

In [ ]:
c

array([45])

In [ ]:
b=a[a%5==0]
c=b[b%3==0]

In [ ]:
c

array([45])

**write a numpy program to create 2d array 4*4 and print diagonal elements of the array**

In [ ]:
data=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a=np.array(data,dtype=int)

In [ ]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a.shape

(4, 4)

In [ ]:
a.ndim

2

In [ ]:
print(a[[0,1,2,3],[0,1,2,3]])

[ 1  6 11 16]


In [ ]:
a.itemsize

8

4.2

In [ ]:
data1={
    "city":['delhi','beiging','washington','tokyo','moscow'],
    "Happyness_index_male":[60,40,70,65,85],
    "Happyness_index_female":[30,60,70,55,75]
}
print(type(data1))

<class 'dict'>


In [ ]:
a=pd.DataFrame(data1)

In [ ]:
print(type(a))
a

<class 'pandas.core.frame.DataFrame'>


city  Happyness_index_male  Happyness_index_female
0       delhi                    60                      30
1     beiging                    40                      60
2  washington                    70                      70
3       tokyo                    65                      55
4      moscow                    85                      75

In [ ]:
a.to_csv("Happy_Index.csv",index=False)

In [ ]:
data_file=pd.read_csv("Happy_Index.csv")

In [ ]:
data_file

city  Happyness_index_male  Happyness_index_female
0       delhi                    60                      30
1     beiging                    40                      60
2  washington                    70                      70
3       tokyo                    65                      55
4      moscow                    85                      75

In [ ]:
a=np.arange(0,25,dtype=int)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
print(a[5:10:2])

[5 7 9]


In [ ]:
print(a[a%3==0])

[ 0  3  6  9 12 15 18 21 24]


In [ ]:
print(a[::-1])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1
  0]


In [ ]:
data=[[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13],[13,14,15,16,17],[17,18,19,20,21]]
a=np.array(data,dtype=int)

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17],
       [17, 18, 19, 20, 21]])

In [ ]:
a.shape

(5, 5)

In [ ]:
a.ndim

2

In [ ]:
b=np.fliplr(a)

In [ ]:
print(b)

[[ 5  4  3  2  1]
 [ 9  8  7  6  5]
 [13 12 11 10  9]
 [17 16 15 14 13]
 [21 20 19 18 17]]


In [ ]:
print(b[1:4,1:4])

[[ 8  7  6]
 [12 11 10]
 [16 15 14]]
