<a href="https://colab.research.google.com/github/ShubhamDhakarey/Solve_Question/blob/main/Numpy_Slice_Advance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
a=np.arange(20)
s=slice(0,20,4)

In [ ]:
print(a[s])

[ 0  4  8 12 16]


In [ ]:
b=a[2:8:2]
print(b)

[2 4 6]


In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
b=a[5]
print(b)

5


In [ ]:
print(a[2:])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(a[2:5])

[2 3 4]


**Multi Dimemsional array
**

In [ ]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])

In [ ]:
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [ ]:
print(a[:3,:1])

[[1]
 [3]
 [4]]


In [ ]:
print(a[:1])

[[1 2 3]]


In [ ]:
print(a[:3,1])

[2 4 5]


In [ ]:
print(a[...,1])

[2 4 5]


In [ ]:
print(a[1,...])

[3 4 5]


In [ ]:
print(a[1,:3])

[3 4 5]


In [ ]:
print(a[...,1:])

[[2 3]
 [4 5]
 [5 6]]


In [ ]:
print(a[:3,1:3])

[[2 3]
 [4 5]
 [5 6]]


In [ ]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [ ]:
print(a[1:,1:])

[[4 5]
 [5 6]]


In [ ]:
print(a[2:,2:])

[[6]]


In [ ]:
x=np.array([[1,2],[3,4],[5,6]])

In [ ]:
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
y=x[[1,2],[1,1]]

In [ ]:
print(y)

[4 6]


In [ ]:
y=x[[1],[1]]
print(y)

[4]


In [ ]:
x=np.array([[0,1,2,3],[3,4,5,6],[6,7,8,9],[9,10,11,12]])
print(x)

[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]]


In [ ]:
row=np.array([[0,0],[3,3]])
col=np.array([[0,2],[0,2]])

In [ ]:
y=x[row,col]
print(y)

[[ 0  2]
 [ 9 11]]


In [ ]:
print(x[[0,1,2,3],[0,1,2,3]])

[ 0  4  8 12]


In [ ]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(x[1:4,1:3])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [ ]:
print(x[x>=5])

[ 5  6  7  8  9 10 11]


In [ ]:
a=np.array([np.nan,1,2,np.nan,3,4,5])

In [ ]:
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [ ]:
a=np.array([1,2+6j,5,3.5+5j])

In [ ]:
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [ ]:
print(a[~np.iscomplex(a)])

[1.+0.j 5.+0.j]


In [ ]:
a=np.array([0,1,2])
a

array([0, 1, 2])

In [ ]:
m=np.ones((3,3))

In [ ]:
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
m+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
b=np.arange(3)
a=np.arange(3).reshape(3,1)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
m=np.ones((2,3))
a=np.arange(3)

In [ ]:
m+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
a+m

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
a=np.arange(0,60,5)

In [ ]:
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
a=a.reshape(3,4)

In [ ]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [ ]:
c=[]
for x in np.nditer(a):
  c.append(int(x))
print(c)
  

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]
